---
title: "Unit test intro"
format: html
editor: visual
---

```{r}
library(testthat)
library(here)
library(palmerpenguins)
```

```{r}
mean_range <- function(df) {
  col_means <- apply(X = df, MARGIN = 2, FUN = mean, na.rm = TRUE)
  col_mean_max <- max(col_means)
  col_mean_min <- min(col_means)
  print(c(col_mean_max, col_mean_min))
}

mean_range(mtcars)
```

```{r}
expect_length(mean_range(mtcars), 2)
```

```{r}
expect_true(mean_range(mtcars)[1] >= mean_range(mtcars)[2])

expect_type(mean_range(mtcars),"double")

expect_true(is.numeric(mean_range(mtcars)))
```

### Source a script

```{r}
source(here::here("src", "food_cart_functions.R"))

name_cart(food = "lasagna", animal = "giraffe")
```

```{r}
# Pull in the cork_oak_growth R script
source(here::here("src", "cork_oak_growth.R"))

height_t2(height_t1 = 8, t1 = 2, t2 = 7)

# Use height_t2 function to calculate the height along a sequence of times.
t2_vec <- seq(from = 1, to = 10, by = 1)
height_t2(height_t1 = 8, t1 = 2, t2 = t2_vec)

# Check the error message
height_t2(height_t1 = 12, t1 = 5, t2 = 1)
```
